# Generated by Django 4.2.30 on 2026-07-01 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NameServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.GenericIPAddressField()),
                ('config_dir', models.CharField(default='/etc/bind', max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nameservers',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('zone_type', models.CharField(choices=[('forward', 'Forward'), ('reverse', 'Reverse')], default='forward', max_length=10)),
                ('ip_version', models.IntegerField(choices=[(4, 'IPv4'), (6, 'IPv6')], default=4)),
                ('serial', models.PositiveBigIntegerField(default=1)),
                ('refresh', models.PositiveIntegerField(default=3600)),
                ('retry', models.PositiveIntegerField(default=900)),
                ('expire', models.PositiveIntegerField(default=604800)),
                ('minimum_ttl', models.PositiveIntegerField(default=86400)),
                ('default_ttl', models.PositiveIntegerField(default=3600)),
                ('is_dirty', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones_created', to=settings.AUTH_USER_MODEL)),
                ('nameservers', models.ManyToManyField(blank=True, related_name='zones', to='dns_manager.nameserver')),
            ],
            options={
                'db_table': 'zones',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('record_type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('NS', 'NS'), ('PTR', 'PTR'), ('SOA', 'SOA'), ('SRV', 'SRV'), ('TXT', 'TXT'), ('CAA', 'CAA')], db_index=True, max_length=10)),
                ('ttl', models.PositiveIntegerField(blank=True, null=True)),
                ('value', models.TextField()),
                ('priority', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_created', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dns_manager.zone')),
            ],
            options={
                'db_table': 'records',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('sync', 'Sync'), ('login', 'Login'), ('logout', 'Logout'), ('login_fail', 'Login Failed')], max_length=20)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.PositiveIntegerField(null=True)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['is_dirty'], name='zones_is_dirt_ab6739_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['zone', 'record_type'], name='records_zone_id_43136e_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['name'], name='records_name_be2597_idx'),
        ),
    ]
