# Generated by Django 4.2.30 on 2026-09-30 22:18

import re
from pathlib import Path

from django.conf import settings
from django.db import migrations, models

_SERIAL_RE = re.compile(r'(\d+)\s*;\s*Serial')


def backfill_published(apps, schema_editor):
    """Publish each zone's last validated version, so agents keep serving it.

    Preferred source is the zone file the sync pipeline last wrote centrally
    (it passed named-checkzone), when its serial matches the zone's. Failing
    that, a zone with no pending edits is rendered from its records, which is
    what agents were served until now. A zone with pending edits and no
    matching file stays unpublished until its next successful sync.
    """
    from apps.dns_manager.zone_engine.generator import render_zone

    Zone = apps.get_model('dns_manager', 'Zone')
    zones_dir = Path(getattr(settings, 'BIND_ZONES_DIR', '/etc/bind/zones'))
    for zone in Zone.objects.all():
        content = ''
        try:
            text = (zones_dir / f'{zone.name}.zone').read_text(encoding='utf-8')
            m = _SERIAL_RE.search(text)
            if m and int(m.group(1)) == zone.serial:
                content = text
        except OSError:
            pass
        if not content and not zone.is_dirty:
            content = render_zone(zone)
        if content:
            zone.published_content = content
            zone.published_serial = zone.serial
            zone.save(update_fields=['published_content', 'published_serial'])


class Migration(migrations.Migration):

    dependencies = [
        ('dns_manager', '0003_nameserver_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='published_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='zone',
            name='published_serial',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_published, migrations.RunPython.noop),
    ]
