# Generated by Django 4.2.30 on 2026-10-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_manager', '0005_zone_sync_lock_optional_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameserver',
            name='agent_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nameserver',
            name='agent_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
